import type { RelationKind, TheoryRule } from './types';

const omt = (chapter: string, title: string) => ({ title, url: `https://viva.pressbooks.pub/openmusictheory/chapter/${chapter}/` });
const substitution = { title: 'Berklee · Chord substitution', url: 'https://online.berklee.edu/takenote/reharmonization-simple-substitution/' };
const rule = (title: string, conditions: string[], limits: string[], sources: TheoryRule['sources']): TheoryRule => ({ title, conditions, limits, sources, version: 'harmony-v1' });
export const KNOWLEDGE: Record<RelationKind, TheoryRule> = {
    dominant: rule('Dominant → target', ['Declared major/minor target', 'Global key and local target remain separate'], ['Dominant quality alone does not establish function', 'Tonicization is not proof of modulation'], [omt('tonicization', 'Open Music Theory · Tonicization')]),
    fifths: rule('Motion of fifths', ['Root interval: descending fifth / ascending fourth'], ['Root motion is a fact, not a functional verdict'], [omt('ii-v-i', 'Open Music Theory · ii–V–I')]),
    'ii-v': rule('Prepare the dominant', ['Major target: ii7–V7', 'Minor target: iiø7–V7'], ['Target is an explicit local frame', 'An incomplete ii–V need not actually resolve'], [omt('ii-v-i', 'Open Music Theory · ii–V–I')]),
    tritone: rule('Same target · different bass', ['Compare dominant sevenths with roots a tritone apart', 'Third and seventh exchange pitch-class roles'], ['Enharmonic equivalence does not erase spelling', 'Melody and voicing can prevent a useful substitution'], [omt('substitutions', 'Open Music Theory · Substitutions')]),
    'tonic-sub': rule('Tonic-family comparison', ['Jazz/pop major-key lens', 'Compare Imaj7, iii7 and vi7 in the declared key'], ['Common tones do not guarantee interchangeability', 'Classical phrase functions can differ'], [substitution]),
    predominant: rule('Predominant-family comparison', ['Compare ii and IV preparations of the same V', 'Use minor-key qualities in a minor frame'], ['Predominant describes a role before a dominant, not every IV occurrence'], [omt('intro-to-harmony', 'Open Music Theory · Harmonic functions'), substitution]),
    'minor-sub': rule('Subdominant minor', ['Major key borrowing from parallel minor', 'Compare iv7, iiø7 and ♭VImaj7'], ['Borrowed does not automatically mean subdominant minor', 'Family comparison does not prescribe the next chord'], [{ title: 'Berklee · Voice leading for guitar', url: 'https://online.berklee.edu/takenote/voice-leading-for-guitar/' }, omt('modal-mixture', 'Open Music Theory · Modal mixture')]),
    leading: rule('Leading-tone approach', ['Leading-tone root a semitone below the target', 'Fully diminished seventh shown with explicit spelling'], ['The same sounding set can have other roots and targets', 'A rootless V7♭9 reading is an interpretation, not identical chord identity'], [omt('tonicization', 'Open Music Theory · Tonicization')]),
    'common-tone': rule('Common-tone diminished', ['A retained target root with neighboring voices'], ['A shared note alone does not prove an embellishing function', 'Shown as a contextual possibility'], [omt('jazz-embellishing-chords', 'Open Music Theory · Embellishing chords')]),
    passing: rule('Passing diminished', ['Preceding, diminished and following chord required', 'Inspect chromatic root motion separately from applied function'], ['Passing and applied leading-tone readings may coexist', 'Chord symbols alone do not establish rhythm or actual bass motion'], [omt('jazz-embellishing-chords', 'Open Music Theory · Embellishing chords')]),
    cadence: rule('Cadence observation', ['Ending location, bass and upper voice are explicit observations'], ['A V–I pair alone is not a cadence', 'This observer does not analyze a complete phrase or composition'], [omt('intro-to-harmony', 'Open Music Theory · Cadences and phrase endings')]),
};
