import type { RelationKind, TheoryRule } from './types';

const omt = (chapter: string, title: string) => ({ title, url: `https://viva.pressbooks.pub/openmusictheory/chapter/${chapter}/` });
const substitution = { title: 'Berklee · Chord substitution', url: 'https://online.berklee.edu/takenote/reharmonization-simple-substitution/' };
const rule = (title: string, conditions: string[], limits: string[], sources: TheoryRule['sources']): TheoryRule => ({ title, conditions, limits, sources, version: 'harmony-v1' });
export const KNOWLEDGE: Record<RelationKind, TheoryRule> = {
    dominant: rule('Dominant → target', ['Declared major/minor target', 'Global key and local target remain separate'], ['Dominant quality alone does not establish function', 'Tonicization is not proof of modulation'], [omt('tonicization', 'Open Music Theory · Tonicization')]),
    'dominant-colour': rule('Dominant colours', ['Same V root and target as Dominant → target', 'Jazz/pop: 9, 13, 7♭9, 7♯9, 7♭5, 7♯5, 7sus4', 'Classical: V9, V♭9 and dominants with an altered 5th', '9ths and a lowered 5th fall by step; a raised 5th rises; retained tones hold'], ['Colour does not change the 3rd–♭7 resolution; 7sus4 has no 3rd and so no tritone', 'Altered dominants are not interchangeable: melody, voicing and style decide', 'Natural 9th/11th/13th without a retained or stepwise destination stay unconnected', 'Classical V13 (13th leaping to 1̂) is not a pitch-class correspondence and is not shown', 'No chord-scale recommendation'], [omt('altered-and-extended-dominant-chords', 'Open Music Theory · Altered and extended dominant chords'), omt('substitutions', 'Open Music Theory · Substitutions')]),
    fifths: rule('Motion of fifths', ['Root interval: descending fifth / ascending fourth'], ['Root motion is a fact, not a functional verdict'], [omt('ii-v-i', 'Open Music Theory · ii–V–I')]),
    'ii-v': rule('Prepare the dominant', ['Major target: ii7–V7', 'Minor target: iiø7–V7'], ['Target is an explicit local frame', 'An incomplete ii–V need not actually resolve'], [omt('ii-v-i', 'Open Music Theory · ii–V–I')]),
    tritone: rule('Same target · different bass', ['Compare dominant sevenths with roots a tritone apart', 'Third and seventh exchange pitch-class roles'], ['Enharmonic equivalence does not erase spelling', 'Melody and voicing can prevent a useful substitution'], [omt('substitutions', 'Open Music Theory · Substitutions')]),
    'tonic-sub': rule('Tonic-family comparison', ['Jazz/pop lens', 'Major: compare Imaj7, iii7 and vi7', 'Minor: compare im7 and the relative-major ♭IIImaj7'], ['Common tones do not guarantee interchangeability', 'Minor ♭VImaj7 is a subdominant-minor chord in jazz function charts and a deceptive target in classical analysis, so it is not listed', 'Classical phrase functions can differ'], [substitution]),
    predominant: rule('Predominant-family comparison', ['Compare ii and IV preparations of the same V', 'Use minor-key qualities in a minor frame'], ['Predominant describes a role before a dominant, not every IV occurrence'], [omt('intro-to-harmony', 'Open Music Theory · Harmonic functions'), substitution]),
    neapolitan: rule('Neapolitan sixth', ['Classical lens · tonic-family target at the key center', 'Major triad on ♭2̂ with 4̂ in the bass (♭II6)', '♭II6–V7–I: ♭2̂ falls to the leading tone, ♭6̂ to 5̂, 4̂ is retained as the 7th of V7'], ['A chromatic version of ii6/ii°6 with the same predominant role', 'Passing through a cadential 6/4 or doubling choices are not shown', 'Jazz/pop ♭IImaj7 is not this rule'], [omt('bii6', 'Open Music Theory · Neapolitan sixth chords')]),
    mixture: rule('Borrowed chords', ['Major key and a major tonic-family target at the key center', 'Same scale degree: diatonic chord beside its parallel-minor form (iiø7, ♭III, iv, ♭VI, ♭VII)', 'Both lenses: this is a pitch-collection relation'], ['Borrowing names the source collection, not a function; Subdominant minor and Backdoor are separate functional readings', 'In common-practice repertoire iv, ii°/iiø7 and ♭VI are the usual mixture chords; ♭III and ♭VII are more typical of later and popular styles', '♭VII also belongs to Mixolydian', 'Minor keys: the Picardy third is observed under Cadence', 'Comparison does not prescribe the next chord'], [omt('modal-mixture', 'Open Music Theory · Modal mixture')]),
    'minor-sub': rule('Subdominant minor', ['Major key borrowing from parallel minor', 'Compare iv7, iiø7 and ♭VImaj7 as one subdominant-minor family'], ['A functional reading of borrowed ♭6̂ chords; Borrowed chords shows the colour relation by degree', 'Borrowed does not automatically mean subdominant minor', 'Family comparison does not prescribe the next chord'], [{ title: 'Berklee · Voice leading for guitar', url: 'https://online.berklee.edu/takenote/voice-leading-for-guitar/' }, omt('modal-mixture', 'Open Music Theory · Modal mixture')]),
    backdoor: rule('Backdoor → tonic', ['Jazz/pop major tonic-family target at the key center', 'Compare ♭VII7–I and iv7–♭VII7–I', '♭VII7 fifth falls to tonic third; seventh falls to tonic fifth'], ['This bounded explorer excludes blues-tonic I7 and local backdoor targets, not the theory itself', 'Parallel-minor source does not make every ♭VII7 a backdoor; a ♭VII triad is shown as a borrowed colour', 'A supplied example is not an observed cadence'], [{ title: 'Learn Jazz Standards · Backdoor progression', url: 'https://www.learnjazzstandards.com/blog/learning-jazz/jazz-theory/backdoor-progression/' }]),
    leading: rule('Leading-tone approach', ['Leading-tone root a semitone below the target', 'Fully diminished seventh shown with explicit spelling'], ['The same sounding set can have other roots and targets', 'A rootless V7♭9 reading is an interpretation, not identical chord identity'], [omt('tonicization', 'Open Music Theory · Tonicization')]),
    'common-tone': rule('Common-tone diminished', ['A retained target root with neighboring voices', 'Analytical neighbor spelling is distinct from diminished chord identity'], ['A shared note alone does not prove an embellishing function', 'Minor targets retain the third and root in this illustration; the fifth receives the moving voices', 'Shown as a contextual possibility'], [omt('jazz-embellishing-chords', 'Open Music Theory · Embellishing chords'), { title: 'Open Music Theory · Common-tone chords', url: 'https://viva.pressbooks.pub/openmusictheorycopy/chapter/common-tone-chords/' }]),
    passing: rule('Passing diminished', ['Preceding, diminished and following chord required', 'Inspect chromatic root motion separately from applied function'], ['Passing and applied leading-tone readings may coexist', 'Chord symbols alone do not establish rhythm or actual bass motion'], [omt('jazz-embellishing-chords', 'Open Music Theory · Embellishing chords')]),
    cadence: rule('Ending observation', ['Phrase ending is required for cadence claims, not for motion observations', 'PAC/IAC needs confirmed bass and final soprano', 'Phrygian: minor iv6–V with confirmed ♭6–5 bass', 'Deceptive targets are triadic vi in major / ♭VI in minor'], ['A V–I pair alone is not a cadence', 'Plagal closure and deceptive cadence/avoidance differ between analyses', 'Classical half-cadence conventions vary; dominant seventh/inversion receives no strict confirmation', 'This observer does not analyze a complete phrase or composition'], [omt('intro-to-harmony', 'Open Music Theory · Cadences and phrase endings'), omt('modal-mixture', 'Open Music Theory · Picardy third'), { title: 'UCSB · Cadences', url: 'https://rothfarb.faculty.music.ucsb.edu/courses/160A/cadences.html' }, { title: 'San Francisco Conservatory of Music · Cadences', url: 'https://sfcm.edu/sites/default/files/2024-04/cadences.pdf' }]),
};
