"""Reproduce geometry-um-v1 constants with independent Decimal constructions."""
from decimal import Decimal, localcontext, ROUND_HALF_UP
from hashlib import sha256
from pathlib import Path

def values(precision, logarithmic):
    with localcontext() as ctx:
        ctx.prec = precision
        return [int((Decimal(10)**12 * ((-Decimal(f)/12 * Decimal(2).ln()).exp()
                    if logarithmic else Decimal(2) ** (-Decimal(f)/12))).to_integral_value(rounding=ROUND_HALF_UP))
                for f in range(37)]

q = values(80, False)
assert q == values(110, True)
digest = sha256(','.join(map(str, q)).encode()).hexdigest()
target = Path(__file__).resolve().parents[2] / 'src/domain/chord/engine/geometryTable.ts'
content = ('// geometry-um-v1; generated by scripts/engine-integration/geometry-table.py.\n'
           '// Decimal power (80 digits) independently checked with exp/log (110 digits).\n'
           f"export const GEOMETRY_TABLE_SHA256 = '{digest}';\n"
           'export const WIRE_REMAINDER_Q = Object.freeze([\n    ' + ', '.join(map(str, q)) + '\n]);\n')
if target.exists():
    assert target.read_text() == content, 'Checked-in table differs; numeric version must be reviewed.'
else:
    target.write_text(content, newline='\n')
print(digest)
